### ISSUE TITLE
Input Data Class and JSON Schema

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbag#19]
## The problem the component solves

A mailbag must accept and manage data from multiple different types of email export formats. To manage this, we need an abstract class defining the API for each format parser and a JSON schema to output this data.

## Type of component

- [ ] Core
- [x] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [ ] GUI
- [ ] Distribution

## Expected contribution

- [ ] Pull Request
- [x] Comment with proposed solution

## Major challenges or things to keep in mind

This data must contain all the data to be put in mailbag.csv, as well as the content of the email that will be used to create derivatives. More data is also likely to be necessary.

Mailbags can also be created from PDFs for legacy purposes, but its likely that it won't be feasible to parse metadata from them, so not all this data will be mandatory.

**Comment by gwiedeman** [comment]
At least on Windows I'm getting an error after running `setup.py` in a virtualenv. Seems like the parsers directory has to be listed somewhere no?

Script:
```
import mailbag
mailbag.gui()
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\greg\win\mtest1.py", line 1, in <module>
    import mailbag
  File "C:\Users\greg\win\python-virtual-environments\mailbag1\lib\site-packages\mailbag-0.0.1-py3.9.egg\mailbag\__init__.py", line 10, in <module>
    from .parser import EmailFormatParser
  File "C:\Users\greg\win\python-virtual-environments\mailbag1\lib\site-packages\mailbag-0.0.1-py3.9.egg\mailbag\parser.py", line 44, in <module>
    import_parsers()
  File "C:\Users\greg\win\python-virtual-environments\mailbag1\lib\site-packages\mailbag-0.0.1-py3.9.egg\mailbag\parser.py", line 37, in import_parsers
    for filename in listdir(parser_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\greg\\win\\python-virtual-environments\\mailbag1\\lib\\site-packages\\mailbag-0.0.1-py3.9.egg\\mailbag\\parsers'
```

**Comment by gwiedeman** [comment]
Email RFC [https://datatracker.ietf.org/doc/html/rfc2822](https://datatracker.ietf.org/doc/html/rfc2822)
